### PR TITLE
Log error, don't crash, if socket closes mid-send

### PR DESCRIPTION
**Pull request by carver**
Split from #81 

Error will always be the same type, no need to log it.

Other conversation: https://github.com/ethereum/utp/pull/81#discussion_r1234472553

Ideally, we would detect somehow that it was a normal shutdown, and we would just silently exit. But if it happens at a surprising time, then it is valuable to have the log. Warn seems like about the right level for that, especially since it typically doesn't trigger very often.

### CODE REVIEW

**Review by jacobkaufmann — COMMENTED** [review]
maybe we don't want to panic, but I don't think a log is sufficient. if the channel to the socket is closed, then the connection cannot progress, since it will be unable to communicate data and/or acknowledgements. if we don't panic, then we should close with an error.

**Comment by carver** [comment]
I see where you're going. I think what's happening is that there's a bug that causes the socket to disappear before the connection completes. (This is possibly something that could be fixed by adding an internal flush, like #89 )

But the current behavior of panicking is unacceptable, because it causes flaky test failures. Changing the behavior to cause an error in the shutdown or connection result would have the same problem, since the test unwrap's these results (correctly, IMO).

I am starting to run out of time to work on utp stuff, other things need my attention. How about I add an issue to track down why the connection sometimes keeps running after the socket is dropped, and we merge this patch until then?

**Comment by carver** [comment]
Ok, I tried something that closes the connection with an error if the socket is unavailable for writes. I kind of don't think it's worth this much extra error handling in order to shut down the connection, just to deal with an occasional flaky issue that's only showing up during tests (some kind of race with shutting the connection down).

My intuition is to just go back to the first commit in this PR, but I wanted to show you this in case you had a better idea how to implement shutting down the connection.

**Comment by carver** [comment]
Ok, my next thought is that we can go *back* to panicking everywhere, except while the connection is handling the final steps of closing down (which I think is where it's happening anyway). It still means having `transmit()` return a result, but we can just `expect()` it everywhere except for where we handle setting the state to `Closed`.

**Pull request merged**
